import type { Metadata } from "next";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from 'next-intl'
import { ReduxProviders } from "@/app/reduxProvider";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale()
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ReduxProviders>
            <Providers>
              {children}
            </Providers>
          </ReduxProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
